### ISSUE TITLE
Apex_PU not properly configured

### ISSUE THREAD

**Issue by lmfmsilva** [araczkowski/docker-oracle-apex-ords#5]
Hi,

If you look at /tomcat/logs/catalina.* you will see:
SEVERE [localhost-startStop-1] . The username or password for the connection pool named apex_pu, are invalid, expired, or the account is locked

This problem may be related to the fact that static workspace files (in an Apex application) can't be found by Tomcat and/or Ords (404 not found).

Best regards,

Luís Silva

**Comment by araczkowski** [comment]
Hi @lmfmsilva 

it's because the Oracle REST Data Service in the apex_pu.xml is not configured correctly.

I will check this deeper but as a workaround you can:
1.  in console
```
ssh root@localhost -p 49160
vim /u01/ords/conf/apex_pu.xml
```
change the password to your password and the username to APEX_REST_PUBLIC_USER
![image](https://cloud.githubusercontent.com/assets/1263968/21691292/2fed3c04-d378-11e6-8ca2-c42cd2254c0b.png)
`service tomcat restart`
`tail -f  /tomcat/logs/catalina.out`

2. in browser go to http://localhost:8080/ords

now should be OK

**Comment by lmfmsilva** [comment]
Hi Andrzej ,

Even though the workaround clears the error, the fundamental issue is that ords doesn't seem able to serve workspace static files (I suspect that static application files as well).

I tried to validate the ords.war:
java -jar /tomcat/webapps/ords.war validate
(used the localhost, sys/secret params)
But the connection fails:
WARNING: Failed to connect to user SYS AS SYSDBA jdbc:oracle:thin:@localhost:1521:xe 
IO Error: Connection reset

Any ideas?

**Comment by araczkowski** [comment]
now I noticed that you have a problem with the serving static APEX files via ORDS, strange  
(previously I thought the your problem is with Oracle REST)

OK, tell me more:

1. Which option?
[Own image](https://github.com/araczkowski/docker-oracle-apex-ords#option-1-own-docker-image-with-custom-password)
or
[Prebuild image from docker hub](https://github.com/araczkowski/docker-oracle-apex-ords#option-2-get-the-prebuilt-image-from-docker-hub)

2. Which version?
the newest APEX 5.1 and ORDS 3.0.9
or
older version

3. Are you able to connect to the container via ssh?
(https://github.com/araczkowski/docker-oracle-apex-ords#connect-via-ssh-to-server-with-following-setting)

4. send me a print screen from your browser console, what can you see on this link: http://localhost:8080/ords/apex
![image](https://cloud.githubusercontent.com/assets/1263968/21745250/a6c776f4-d527-11e6-9fbb-1cb9e85ba4e5.png)

**Comment by lmfmsilva** [comment]
Hi,

1) Prebuilt image from hub.docker.com
2) The newest version (apex 5.1)  - but the problem also occured in the previous version
3) Yes I am
4) See atached image:
![apex_login](https://cloud.githubusercontent.com/assets/1859387/21746384/ceb2444c-d53a-11e6-89af-7925690a0e15.png)

I was able to solve this problems by repeating the ords.war setup command (and restarting tomcat):
root@8845bb4fb5e9:/tomcat/webapps# java -jar ords.war setup
