### ISSUE TITLE
Page Designer is extremely slow

### ISSUE THREAD

**Issue by XDecs** [araczkowski/docker-oracle-apex-ords#8]
When I'm in the Page Designer view of any application, the Save button action takes to much to accomplish. Even if the change was minimum it takes **15 -20 seconds** to process the Save action.

I already tried to improve tomcat and the database with no luck and at this time I'm not sure if the problem is related to the docker container or any specific configuration on the Application Express installation.

**Comment by araczkowski** [comment]
the performance issue is on your local environment or on some cloud (amazon etc.)?

**Comment by eaespinoza0** [comment]
I have also experienced this issue in both cloud (AWS) and locally

**Comment by XDecs** [comment]
Is on my local environment.

**Comment by XDecs** [comment]
For the record I used the **Option 2** (Option 2. Get the prebuilt image from docker hub).

**Comment by araczkowski** [comment]
well this kind of software has a problem with performance by design ;), I mean that the whole Oracle/Java stack needs lot of resources (memory and cpu)
I just checked on my ultrabook with i7 and 16gb ram, according to htop on the docker container when I'm using APEX the cpus usage is often 100% on each core and memory usage is very closed to 16GB
but the page designer with this resources works pretty smoothly

what I can suggest:
1. go to the container -> ssh root@<containerhost> -p 49160
2. install the htop -> apt update && apt install htop
3. execute htop in the container
4. open the apex page designer on your local machine and try to submit a page after changes
5. check the resources  in the htop  
if you don't have enough memory it will be painful to use

**Comment by XDecs** [comment]
Thanks! I'll do it now and I'll let you know!

I have a Macbook Pro Mid 2017 core i7 and 16GB Ram, so... I would expect a behavior close to yours.

**Comment by XDecs** [comment]
@araczkowski Thanks for your suggestions. Now my local environment works really fast and the ec2 machine (t2.medium) has a better respond time now it's close to 13 seconds.

I believe that the apt update command did the trick.

I'll continue with my testings and check if I can low that a little bit more (but probably I would need a better connection and a bigger machine).


Thanks for your help. Appreciate it!
